---
sudo: false
language: ruby
rvm:
  - 2.4
  - 2.5
  - 2.6

gemfile:
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile

matrix:
  exclude:
  - rvm: 2.4
    gemfile: gemfiles/rails_6.0.gemfile
  - rvm: 2.5
    gemfile: gemfiles/rails_6.0.gemfile

cache: bundler
